name: micro_dart_runtime
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
   collection: any

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
