name: cli_plugin1
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
 micro_dart_runtime: 
    path: ../../micro_dart_runtime
 cli_example:
    path: ../cli_example/

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
