name: micro_dart_flutter
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  micro_dart_runtime: 
    path: ../micro_dart_runtime

dev_dependencies:
  micro_dart_generator: 
    path: ../micro_dart_generator
